[package]
name = "dslr"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.16.1"
ndarray-rand = "0.15.0"
serde = { version = "1.0.1", features = ["derive"] }
serde_json = "1.0.140"

[lib]
path = "lib/lib.rs" 