[package]
name = "dslr"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.16.1"
ndarray-rand = "0.15.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
rand = "0.9.0"
clap = { version = "4.4", features = ["derive"] }


[lib]
path = "lib/lib.rs" 